name: Image Dev

on:
  push:
    branches:
      - "main"
    paths:
      - "docker/dev.Dockerfile"
      - "ops/apt/**"
      - ".github/workflows/image-dev.yaml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: docker/setup-buildx-action@master
      - uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@master
        with:
          context: .
          file: docker/dev.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/common-dev:latest
            ghcr.io/${{ github.repository_owner }}/common-dev:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/common-dev:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/common-dev:cache,mode=max
